service: travelex-william-serverless-example2

provider:
  name: aws
  runtime: nodejs8.10

plugins:
  - serverless-offline

functions:
  hello:
    handler: handler.hello
    events:
      - http: GET hello